### ISSUE TITLE
Player list incorrectly displaying name of client.

### ISSUE THREAD

**Issue by penguin0616** [Roblox/Core-Scripts#1002]
On occasion when I join a game, the leaderboard says my name is 'Player', even though that is not the case.
![image](https://user-images.githubusercontent.com/23770056/28688947-635937d6-72d9-11e7-8883-66cc91dbb088.png)

**Comment by boynedmaster** [comment]
Can you find a way to reproduce this?

**Comment by iLordPenguin** [comment]
The last time I've seen it was that picture, taken and posted here the same day it occurred.
I haven't seen the bug anymore since, and I can't think of a way to reproduce it since it is extremely rare for me. The only thing I know about it is that it never causes any errors in the developer console.
