### ISSUE TITLE
DevComputerMovementMode is broken

### ISSUE THREAD

**Issue by ricalou** [ROBLOX/Core-Scripts#161]
At the moment, [DevComputerMovementMode](http://wiki.roblox.com/index.php?title=API:Class/Player/DevComputerMovementMode) is broken. Weather you change it on the Properties window, or through a script using *Enum.DevComputerMovementMode*, it has no effect on the player or it's ability to control the character.

This has been tested both in studio and online mode.

**Comment by jmargh** [comment]
We have disabled player scripts in order to address some issues we were seeing with them. DevComputerMovementMode is only used by the default player scripts right now and will have no effect on the old control system, so these enums do nothing right now. We don't have an exact ETA on when we will turn on player scripts again.

For reference, here are all the properties on StarterPlayer that will do nothing until player scripts are turned on again...

DevCameraOcclusionMode
DevComputerCameraMovementMode
DevTouchCameraMovementMode
DevComputerMovementMode
DevTouchMovementMode
EnableMouseLockOption

**Comment by BinaryResolved** [comment]
@ricalou They are all turned back on. Mind closing this?
