### ISSUE TITLE
ServerSocialScript line 145, ServerStarterScript line 56

### ISSUE THREAD

**Issue by Ayukito** [ROBLOX/Core-Scripts#442]
11:30:24  -- OnServerInvoke can only be implemented on the server
11:30:24  -- Script 'Script Context.ServerCoreScripts/ServerSocialScript', Line 145
11:30:24  -- Stack End
11:30:24  -- OnServerEvent can only be used on the server
11:30:24  -- Script 'Script Context.ServerStarterScript', Line 56
11:30:24  -- Stack End

Every game. Local f9 developer console.
Are they localscripts or something?

**Comment by BinaryResolved** [comment]
Maybe a change with the engine.

-----Original Message-----

**Comment by kyle-emmerich** [comment]
Yeah, we discovered a weird little issue where the client thinks it's running the server because it hasn't fully initialized. Since the core scripts run so early, the client started running the server stuff as well.

It'll be fixed in the near future. In the meantime, sorry about the output spam! It won't break anything; that script isn't intended to run on the client anyway.

**Comment by BinaryResolved** [comment]
Ok

-----Original Message-----

**Comment by GitBlox** [comment]
This issue was moved to GitBlox/Core-Scripts#21

**Comment by foreverpower** [comment]
This bug seems to have the unintended consequence of breaking the ServerSocialScript(i.e. follower functionally) and the server dialog script.

This happens because the local versions of the ServerSocialScript and the server dialog script create their own RemoteEvents, which are then incorrectly invoked by the other localscripts instead of invoking the ones created by the server. Thus, the actual server scripts are not receiving the intended data, and thus both of these scripts are not functioning properly in game.

**Comment by kyle-emmerich** [comment]
This should have been fixed on the engine level. I'll have to verify that though. It may not have been released yet.
